### ISSUE TITLE
Service Worker / Optimization

### ISSUE THREAD

**Issue by ehsan-g** [SAY-DAO/frontend#11]
Modify the service worker and improve the Lighthouse score

### TODOs
- [x] Improve Lighthouse score
- [ ] Handle the fallback page when offline
- [ ] Reset caches in case of service worker change
- [ ] Maskable icon in manifest (from the lighthouse)
